name: project_b
description: project B

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  logger: ^1.1.0
  get: ^4.6.5
  syncfusion_flutter_charts: ^20.2.43
  http: ^0.13.5
  web_socket_channel: ^2.2.0
  socket_io_client: ^2.0.0
  intl: ^0.17.0
  equatable: ^2.0.3
  dart_jsonwebtoken: ^2.4.2
  uuid: ^3.0.6
  mongo_dart: ^0.7.4+1
  oktoast: ^3.2.0
  crypto: ^3.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
